// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	PasswordHash sql.NullString `json:"password_hash"`
	Role         string         `json:"role"`
	Status       string         `json:"status"`
	TokenVersion int32          `json:"token_version"`
}
